<a href="https://colab.research.google.com/github/MudassirAli619/Ali/blob/master/4_SalaryEstimation_K_NN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#|Salary Estimation| K-Nearest Neighbour Model

## Importing Libraries

In [ ]:
import pandas as pd #useful for loading the dataset
import numpy as np #to perform array

#Choose Dataset from Local Directory

Not needed if you choose alternative way which is by clicking files which is on left side.

In [ ]:
from google.colab import files
uploaded = files.upload() 

Saving salary.csv to salary.csv


##Load Dataset

In [ ]:
dataset = pd.read_csv('salary.csv') 

## Summarize Dataset

In [ ]:
print(dataset.shape) #This will show no. of rows & columns
print(dataset.head(5)) #This will show top 5 datset

(48842, 5)
   age  educational-num  capital-gain  hours-per-week income
0   25                7             0              40  <=50K
1   38                9             0              50  <=50K
2   28               12             0              40   >50K
3   44               10          7688              40   >50K
4   18               10             0              30  <=50K


## Mapping Salary Data to Binary Value

In [ ]:
income_set = set(dataset['income'])
dataset['income']= dataset['income'].map({'<=50K': 0, '>50K': 1}).astype(int)
print(dataset.head)

<bound method NDFrame.head of        age  educational-num  capital-gain  hours-per-week  income
0       25                7             0              40       0
1       38                9             0              50       0
2       28               12             0              40       1
3       44               10          7688              40       1
4       18               10             0              30       0
...    ...              ...           ...             ...     ...
48837   27               12             0              38       0
48838   40                9             0              40       1
48839   58                9             0              40       0
48840   22                9             0              20       0
48841   52                9         15024              40       1

[48842 rows x 5 columns]>


# Segregate Dataset into X(input/Independent Variable) & Y(Output/Dependent Variable)


In [ ]:
X=dataset.iloc[:, :-1].values
X

array([[   25,     7,     0,    40],
       [   38,     9,     0,    50],
       [   28,    12,     0,    40],
       ...,
       [   58,     9,     0,    40],
       [   22,     9,     0,    20],
       [   52,     9, 15024,    40]])

In [ ]:

y=dataset.iloc[:, -1].values
y

array([0, 0, 1, ..., 0, 0, 1])

## Splitting Dataset into Train & test

In [ ]:
from sklearn.model_selection import train_test_split #From this library we are gonna split the data into train & test.
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0) #it will return 4 variables. X input & Y output train & test variables

# Feature Scaling

we scale our data to make all the features contribute equally to the result

Fit_Transform - fit method is calculating the mean and variance of each of the features present in our data.

Transform - Transform method is transforming all the features using the respective mean and variance,

We want our test data to be a completely new and a suprise set for our model

In [ ]:
from sklearn.preprocessing import StandardScaler #from scikiklearn, we are going to use standard scaler method
sc = StandardScaler() #sc means standard scaler
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test) #transform because we want new data

# Training

In [ ]:
from sklearn.neighbors import KNeighborsClassifier  
classifier= KNeighborsClassifier(n_neighbors=5, metric='minkowski', p=2 )  
classifier.fit(X_train, y_train)  

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

## Predicting, wheather new Employee with age,education.num,capital.gain,hours.per.week will have less than or More than 50K salary

In [ ]:
age = int(input("Enter New Employee age: "))
education_num = int(input("Enter New employee Number of years of education: "))
capital_gain = int(input("Enter New Employee capital gain: "))
hours_per_week = int(input("Enter New Employee hours per week: "))
newEmpl =[[age,education_num,capital_gain,hours_per_week]]
result = classifier.predict(sc.transform(newEmpl)) #standard scalar, model predict will give only two value 0&1
print(result)
if result == 1:
  print("Salary will be >50K")
else:
  print("Salary will be <=50K")

Enter New Employee age: 21
Enter New employee Number of years of education: 17
Enter New Employee capital gain: 1
Enter New Employee hours per week: 48
[1]
Salary will be >50K


## Prediction for all Test Data

In [ ]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 1]
 [0 1]
 ...
 [0 1]
 [0 1]
 [0 1]]


##EVALUATING MODEL - confusion matrix

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)

print("Confusion Matrix: ")
print(cm)

print("Accuracy of the model: {0}%".format(accuracy_score(y_test, y_pred)*100))

Confusion Matrix: 
[[8385  888]
 [1667 1271]]
Accuracy of the model: 79.07624273196299%
