<a href="https://colab.research.google.com/github/MudassirAli619/Ali/blob/master/Ad_Sale_Prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Ad. Sale Prediction from Existing customer - Logistic Regression (Mudassir Ali)

# Importing Libraries

In [2]:
import pandas as pd #Useful for loading the dataset
import numpy as np #to perform array

# Choose Dataset file from Local Directory

In [3]:
from google.colab import files
uploaded= files.upload()

Saving DigitalAd_dataset.csv to DigitalAd_dataset.csv


# Load Dataset

In [4]:
dataset = pd.read_csv('DigitalAd_dataset.csv')

# Summarize Dataset

In [5]:
print(dataset.shape) #no. of rows and columns
print(dataset.head(5)) #Top 5 results of dataset

(30, 3)
   YearsExperience  Salary  Status
0              1.1   39343       0
1              1.3   46205       0
2              1.5   37731       0
3              2.0   43525       0
4              2.2   39891       0


# Segregate Dataset into X(Input/Independent Varaiable) & Y(Output/ Dependent Variable)

In [6]:
X = dataset.iloc[:, :-1].values
X

array([[1.10000e+00, 3.93430e+04],
       [1.30000e+00, 4.62050e+04],
       [1.50000e+00, 3.77310e+04],
       [2.00000e+00, 4.35250e+04],
       [2.20000e+00, 3.98910e+04],
       [2.90000e+00, 5.66420e+04],
       [3.00000e+00, 6.01500e+04],
       [3.20000e+00, 5.44450e+04],
       [3.20000e+00, 6.44450e+04],
       [3.70000e+00, 5.71890e+04],
       [3.90000e+00, 6.32180e+04],
       [4.00000e+00, 5.57940e+04],
       [4.00000e+00, 5.69570e+04],
       [4.10000e+00, 5.70810e+04],
       [4.50000e+00, 6.11110e+04],
       [4.90000e+00, 6.79380e+04],
       [5.10000e+00, 6.60290e+04],
       [5.30000e+00, 8.30880e+04],
       [5.90000e+00, 8.13630e+04],
       [6.00000e+00, 9.39400e+04],
       [6.80000e+00, 9.17380e+04],
       [7.10000e+00, 9.82730e+04],
       [7.90000e+00, 1.01302e+05],
       [8.20000e+00, 1.13812e+05],
       [8.70000e+00, 1.09431e+05],
       [9.00000e+00, 1.05582e+05],
       [9.50000e+00, 1.16969e+05],
       [9.60000e+00, 1.12635e+05],
       [1.03000e+01,

In [7]:
Y=dataset.iloc[:, -1].values
Y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0])

# Splitting Dataset into Train & Test

In [8]:
from sklearn.model_selection import train_test_split #From this library we are gonna split the data into train & test.
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.25, random_state = 0) #it will return 4 variables. X input & Y output train & test variables

# Feature Scaling

we scale our data to make all the features contribute equally to the result

Fit_Transform - fit method is calculating the mean and variance of each of the features present in our data.

Transform - Transform method is transforming all the features using the respective mean and variance,

We want our test data to be a completely new and a suprise set for our model

In [9]:
from sklearn.preprocessing import StandardScaler #from scikiklearn, we are going to use standard scaler method
sc = StandardScaler() #sc means standard scaler
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test) #transform because we want new data

# Training

In [10]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression(random_state = 0)
model.fit(X_train,Y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=0, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

# Predicting, wheather new customer with years of experience & Salary will Buy or Not

In [11]:
exp = int(input("Enter New Customer experience: "))
sal = int(input("Enter New Customer Salary: "))
newCust =[[exp,sal]]
result = model.predict(sc.transform(newCust)) #standard scalar, model predict will give only two value 0&1
print(result)
if result == 1:
  print("Customer will Buy")
else:
  print("Customer won't Buy")

Enter New Customer experience: 5
Enter New Customer Salary: 50000
[0]
Customer won't Buy


#Prediction for all Test Data

In [12]:
Y_pred = model.predict(X_test)
print(np.concatenate((Y_pred.reshape(len(Y_pred),1), Y_test.reshape(len(Y_test),1)),1))

[[0 0]
 [1 0]
 [0 1]
 [0 0]
 [1 0]
 [1 0]
 [1 0]
 [0 0]]


#EVALUATING MODEL - confusion matrix

In [15]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(Y_test, Y_pred)

print("Confusion Matrix: ")
print(cm)

print("Accuracy of the model: {0}%".format(accuracy_score(Y_test, Y_pred)*100))

Confusion Matrix: 
[[3 4]
 [1 0]]
Accuracy of the model: 37.5%
